### PR TITLE
Fixing SSL Error for local dev

### PR DESCRIPTION
**Pull request by Kinfe123**
it can now sync for both remote and local db conn string for mysql and easily portable to pg

### CODE REVIEW

**Comment by Fr3akyMurk** [comment]
Actually going crazy.
These changes causes:
```
Error: connect ETIMEDOUT
    at createConnection2 (/home/mark/next-lucia-auth/node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:44322:35)
    at connectToMySQL (/home/mark/next-lucia-auth/node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:61903:64)
    at Command.<anonymous> (/home/mark/next-lucia-auth/node_modules/.pnpm/drizzle-kit@0.20.14/node_modules/drizzle-kit/bin.cjs:63065:28) {
  code: 'ETIMEDOUT',
  errno: undefined,
  sqlState: undefined
}
```

**Comment by Kinfe123** [comment]
Can you show me the db that you have created locally

**Comment by Fr3akyMurk** [comment]
> Can you show me the db that you have created locally
Elaborate, how do you want me to show it?

**Comment by Kinfe123** [comment]
the mysql db that you have created locally

**Comment by iamtouha** [comment]
it also causes error when running `pnpm run db:studio` to inspect the database.

```bash
 Invalid input  Either "connectionString" or "host", "database" are required for database connection
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Fr3akyMurk** [comment]
> it also causes error when running `pnpm run db:studio` to inspect the database.
> 
> ```shell
>  Invalid input  Either "connectionString" or "host", "database" are required for database connection
>  ELIFECYCLE  Command failed with exit code 1.
> ```

I got a similar something something error but i don't know how i got it.

**Comment by Fr3akyMurk** [comment]
> the mysql db that you have created locally

Are you asking for the connectionstring?
``
DATABASE_URL='postgresql://postgres:POSTGRES@localhost:5432/lucia?ssl={"rejectUnauthorized":false}'
``

**Comment by Kinfe123** [comment]
image
this is mine but you have to make sure you are passing the necessary env var for that and make sure to use `mysql://user:password@localhost:3306/lucia` where lucia is the db that u will be creating `CREATE DATABASE lucia; `with in the mysql shell command

**Comment by Kinfe123** [comment]
> > the mysql db that you have created locally
> 
> Are you asking for the connectionstring? `DATABASE_URL='postgresql://postgres:POSTGRES@localhost:5432/lucia?ssl={"rejectUnauthorized":false}'`


this is pg , u have to change the driver to pg and install pg to to use pg as your primary db

**Comment by Fr3akyMurk** [comment]
> > > the mysql db that you have created locally
> > 
> > 
> > Are you asking for the connectionstring? `DATABASE_URL='postgresql://postgres:POSTGRES@localhost:5432/lucia?ssl={"rejectUnauthorized":false}'`
> 
> this is pg , u have to change the driver to pg and install pg to to use pg as your primary db

Tried with MariaDB (mysql) too, doesn't work regardless.

**Comment by Kinfe123** [comment]
Try this one -` mysql://user:password@localhost:3306/lucia ` can you go create a db with mysql dialect , and with mysql driver as well using this format ...

**Comment by Kinfe123** [comment]
have u tried by checeking out thir pr branch

**Comment by Kinfe123** [comment]
to avoid version conflit issue

**Comment by Fr3akyMurk** [comment]
What?
Yes i know how to switch connection strings based on db's
Yes i have checked out this pr branch, there are no conflicts.

**Comment by Kinfe123** [comment]
hmm.. this is just a simple thing fix .. like first it was not working for mee but now it is working fine but let other tried it and may be ur firewall any proxy issue may hang up HANDSHAKE's and other connection pull/push

**Comment by Fr3akyMurk** [comment]
> hmm.. this is just a simple thing fix .. like first it was not working for mee but now it is working fine but let other tried it and may be ur firewall any proxy issue may hang up HANDSHAKE's and other connection pull/push

My firewall is literally inactive.

**Comment by Fr3akyMurk** [comment]
I'll try switch to pg drivers.

**Comment by Kinfe123** [comment]
@iamtouha  can you also please test it ?

**Comment by Fr3akyMurk** [comment]
Switch to sqlite :trollface: 
No but i don't understand what the issue may be.
I have combed through sql, pg, neon etc etc and i get the same errors.

maybe it's the drizzle version?

**Comment by Fr3akyMurk** [comment]
interesting, i got pg to somewhat work, problem is when i run pnpm db:push i get "No changes detected" despite the fact that my pg server has no tables.

**Comment by Kinfe123** [comment]
> Switch to sqlite :trollface: No but i don't understand what the issue may be. I have combed through sql, pg, neon etc etc and i get the same errors.
> 
> maybe it's the drizzle version?

yeah i have told u that earlieer to make sure we are on the same version to avoid conflits ..

**Comment by Kinfe123** [comment]
> interesting, i got pg to somewhat work, problem is when i run pnpm db:push i get "No changes detected" despite the fact that my pg server has no tables.

Does it applies the changes

**Comment by Fr3akyMurk** [comment]
> > Switch to sqlite :trollface: No but i don't understand what the issue may be. I have combed through sql, pg, neon etc etc and i get the same errors.
> > maybe it's the drizzle version?
> 
> yeah i have told u that earlieer to make sure we are on the same version to avoid conflits ..

Yes and i told you there were no conflicts, i am talking about this projects drizzle version.

**Comment by Fr3akyMurk** [comment]
> > interesting, i got pg to somewhat work, problem is when i run pnpm db:push i get "No changes detected" despite the fact that my pg server has no tables.
> 
> Does it applies the changes

No, it changes nothing.

**Comment by Fr3akyMurk** [comment]
Interesting, i reinstalled the project and reconfigured everything.
I still get ssl errors (ssl wrong version number) however db:push now does things and it is reflected on my db.
however using the project is still a no go because of that ssl error.

**Comment by Kinfe123** [comment]
let me try reproducting the issuee

**Comment by Kinfe123** [comment]
@Fr3akyMurk try using `pnpm drizzle-kit push:mysql` for pushing and `npm drizzle-kit studio` since wee dont need to load the env since it is already on our root folder using dotenv ... and share the result

**Review by iamtouha — APPROVED** [review]

**Comment by iamtouha** [comment]
I think the root cause of the problem is, drizzle config differs depending on the database driver. In new version, drizzle-kit provides `defineConfig` function for defining config object. for `pg` driver, use `connectionString` and for `mysql2` driver, use `uri`. hopefully, it'll solve the issue.

**Comment by iamtouha** [comment]
Here is the documentation for `dbCredentials` object for different databases and drivers- https://orm.drizzle.team/kit-docs/config-reference

**Comment by Fr3akyMurk** [comment]
@iamtouha Not too sure, i think it could be related to planetscales drivers because i read up on it andplanetscale itself does not offer any way to connect to "bring your own" mysql server but rather it connects via http / https to a mysql server via proxy rather than mysql://

**Comment by iamtouha** [comment]
Have you tried separately putting all parameters?
image

**Pull request merged**
